name = "harlow-site"
compatibility_date = "2024-01-01"
workers_dev = true

main = "functions/cron.js"

[assets]
directory = "."
not_found_handling = "single-page-application"
exclude = [".git", ".wrangler", "node_modules", "wrangler.toml", "README.md"]

[[d1_databases]]
binding = "DB"
database_name = "harlow-db"
database_id = "PASTE_YOUR_D1_ID_HERE"

[triggers]
crons = ["0 0 * * *"]